#!/usr/bin/env python3
"""Manage the MaxTAC faceted research corpus."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import json
import re
import shutil
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
LEDGER_SCRIPTS_DIR = SCRIPT_DIR.parent.parent / "maxtac-core-ledger" / "scripts"
sys.path.insert(0, str(LEDGER_SCRIPTS_DIR))

import workspace_db  # noqa: E402


DOC_PREFIX = "R"
EDGE_PREFIX = "CE"
DOC_KINDS = (
    "architecture",
    "invariant",
    "negative-result",
    "open-question",
    "proof-note",
    "hypothesis",
    "triage-summary",
    "model-summary",
    "closure",
    "decision",
    "handoff",
    "reference",
)
DOC_STATUSES = ("draft", "candidate", "observed", "confirmed", "negative", "stale", "superseded", "artifact-only")
EDGE_STATUSES = ("candidate", "observed", "confirmed", "refuted", "stale")
CONFIDENCES = ("high", "medium", "low", "unknown")
EVIDENCE_REQUIRED_STATUSES = {"observed", "confirmed", "negative", "stale", "superseded", "artifact-only"}
EDGE_EVIDENCE_REQUIRED_STATUSES = {"observed", "confirmed", "refuted", "stale"}
CORE_FACETS = {"domain", "subsystem", "boundary", "asset", "actor", "knowledge-kind", "phase"}
VIEW_FILES = ("index.md", "facets.md", "open-questions.md", "graph.mmd")
GENERATED_NOTICE = "<!-- Generated by maxtac-core-corpus. Do not edit by hand. -->"
IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def root_path(value: str | None) -> Path:
    root = Path(value or ".").expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    return root


def relative_to_root(root: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return str(path)


def workspace_path(root: Path, value: str | Path, label: str = "path") -> Path:
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = root / path
    resolved_root = root.resolve()
    resolved_path = path.resolve()
    try:
        resolved_path.relative_to(resolved_root)
    except ValueError as exc:
        raise SystemExit(f"{label} escapes workspace root: {resolved_path}") from exc
    return resolved_path


def corpus_dirs(root: Path) -> dict[str, Path]:
    research = root / "research"
    return {
        "research": research,
        "notes": research / "notes",
        "views": research / "views",
        "artifacts": research / "artifacts",
    }


def ensure_dirs(root: Path) -> None:
    for path in corpus_dirs(root).values():
        path.mkdir(parents=True, exist_ok=True)


def read_text_file(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError as exc:
        raise SystemExit(f"missing text file: {path}") from exc


def write_text_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def parse_tag(value: str) -> dict[str, Any]:
    raw = value.strip()
    weight = 1.0
    source = "manual"
    if not raw:
        raise SystemExit("empty tag")
    if "@" in raw:
        raw, raw_weight = raw.rsplit("@", 1)
        try:
            weight = float(raw_weight)
        except ValueError as exc:
            raise SystemExit(f"invalid tag weight: {value}") from exc
    if "=" in raw:
        facet, tag_value = raw.split("=", 1)
    elif ":" in raw:
        facet, tag_value = raw.split(":", 1)
    else:
        raise SystemExit(f"tag must use facet=value: {value}")
    facet = slug_part(facet, "facet")
    tag_value = slug_part(tag_value, "value")
    if not facet or not tag_value:
        raise SystemExit(f"invalid tag: {value}")
    return {
        "facet": facet,
        "value": tag_value,
        "key": tag_key(facet, tag_value),
        "weight": weight,
        "source": source,
    }


def parse_tags(values: list[str] | None) -> list[dict[str, Any]]:
    tags: list[dict[str, Any]] = []
    seen: set[str] = set()
    for value in values or []:
        for part in re.split(r"[,;\n]+", value):
            if not part.strip():
                continue
            tag = parse_tag(part)
            if tag["key"] not in seen:
                tags.append(tag)
                seen.add(tag["key"])
    return tags


def tag_key(facet: str, value: str) -> str:
    return f"{facet}:{value}"


def slug_part(value: str, default: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9._-]+", "-", value.strip().lower()).strip("-._")
    return cleaned or default


def parse_repeated(values: list[str] | None) -> list[str]:
    result: list[str] = []
    for value in values or []:
        for part in re.split(r"[,;\n]+", value):
            stripped = part.strip()
            if stripped and stripped not in result:
                result.append(stripped)
    return result


def token_set(*values: Any) -> set[str]:
    text = " ".join(str(value or "") for value in values)
    return {part for part in re.split(r"[^a-zA-Z0-9_+-]+", text.lower()) if len(part) > 2}


def fts_query(text: str) -> str:
    parts = sorted(token_set(text))
    return " OR ".join(f'"{part.replace(chr(34), chr(34) + chr(34))}"' for part in parts)


def read_json_value(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"missing JSON file: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"{path}: invalid JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise SystemExit(f"{path}: expected a JSON object")
    return payload


def validate_identifier(value: str, label: str) -> None:
    if not IDENTIFIER_RE.fullmatch(value):
        raise SystemExit(f"invalid SQL {label}: {value}")


def next_id(root: Path, table: str, column: str, prefix: str) -> str:
    validate_identifier(table, "table")
    validate_identifier(column, "column")
    workspace_db.initialize_workspace_db(root)
    pattern = re.compile(rf"{re.escape(prefix)}-(\d{{6}})$")
    scope = f"{table}.{column}"
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        conn.execute("BEGIN IMMEDIATE")
        highest = 0
        rows = conn.execute(f"SELECT {column} FROM {table}").fetchall()
        for row in rows:
            value = str(row[column])
            match = pattern.fullmatch(value)
            if match:
                highest = max(highest, int(match.group(1)))
        counter = conn.execute("SELECT next_value FROM id_counters WHERE scope = ?", (scope,)).fetchone()
        next_value = max(highest + 1, int(counter["next_value"]) if counter else 1)
        conn.execute(
            """
            INSERT INTO id_counters(scope, next_value, updated_at)
            VALUES (?, ?, ?)
            ON CONFLICT(scope) DO UPDATE SET
              next_value=excluded.next_value,
              updated_at=excluded.updated_at
            """,
            (scope, next_value + 1, now()),
        )
        conn.commit()
    return f"{prefix}-{next_value:06d}"


def count_lines(text: str) -> int:
    if not text:
        return 0
    return len(text.splitlines())


def count_words(text: str) -> int:
    return len(re.findall(r"\b\S+\b", text))


def validate_doc_payload(payload: dict[str, Any], body: str, *, strict: bool = True) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    for key in ("doc_id", "title", "kind", "status", "summary", "body_path", "created_at", "updated_at"):
        if not str(payload.get(key, "")).strip():
            errors.append(f"{key} is required")
    if payload.get("kind") not in DOC_KINDS:
        errors.append(f"kind must be one of {', '.join(DOC_KINDS)}")
    if payload.get("status") not in DOC_STATUSES:
        errors.append(f"status must be one of {', '.join(DOC_STATUSES)}")
    tags = payload.get("tags")
    if not isinstance(tags, list):
        errors.append("tags must be an array")
        tags = []
    else:
        tag_keys = [str(tag.get("key", "")) for tag in tags if isinstance(tag, dict)]
        if len(tag_keys) != len(set(tag_keys)):
            errors.append("tags contain duplicates")
        if strict and len(tags) < 2:
            errors.append("at least two tags are required; use --allow-thin only for temporary drafts")
        facets = {str(tag.get("facet", "")) for tag in tags if isinstance(tag, dict)}
        if strict and not facets.intersection({"subsystem", "boundary", "asset", "knowledge-kind"}):
            errors.append("at least one subsystem, boundary, asset, or knowledge-kind tag is required")
        if "knowledge-kind" not in facets:
            warnings.append("missing knowledge-kind tag")
    evidence = payload.get("evidence")
    if not isinstance(evidence, list):
        errors.append("evidence must be an array")
        evidence = []
    if payload.get("status") in EVIDENCE_REQUIRED_STATUSES and not evidence:
        errors.append(f"evidence is required when status is {payload.get('status')}")
    if not str(payload.get("summary", "")).strip():
        errors.append("summary is required")
    if strict and len(str(payload.get("summary", ""))) < 20:
        warnings.append("summary is very short")
    if not body.strip():
        errors.append("body is required")
    if count_lines(body) > 220:
        warnings.append("body is over 220 lines; split the note or use artifact storage for raw output")
    if count_lines(body) > 320:
        errors.append("body is over 320 lines; corpus notes must stay compact")
    return errors, warnings


def validate_edge_payload(payload: dict[str, Any]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    for key in ("edge_id", "src_doc_id", "predicate", "dst_doc_id", "status", "confidence", "created_at", "updated_at"):
        if not str(payload.get(key, "")).strip():
            errors.append(f"{key} is required")
    if payload.get("status") not in EDGE_STATUSES:
        errors.append(f"status must be one of {', '.join(EDGE_STATUSES)}")
    if payload.get("confidence") not in CONFIDENCES:
        errors.append(f"confidence must be one of {', '.join(CONFIDENCES)}")
    if payload.get("status") in EDGE_EVIDENCE_REQUIRED_STATUSES and not str(payload.get("evidence", "")).strip():
        errors.append(f"evidence is required when edge status is {payload.get('status')}")
    if payload.get("src_doc_id") == payload.get("dst_doc_id"):
        warnings.append("edge links a document to itself")
    return errors, warnings


def render_note_markdown(payload: dict[str, Any], body: str) -> str:
    tags = ", ".join(f"{tag['facet']}={tag['value']}" for tag in payload.get("tags", []))
    evidence = payload.get("evidence", [])
    model_refs = payload.get("model_refs", [])
    lines = [
        f"# {payload['title']}",
        "",
        "<!-- MaxTAC corpus note. Use maxtac-core-corpus/scripts/corpus.py to edit indexed metadata. -->",
        "",
        "## Metadata",
        "",
        f"- ID: `{payload['doc_id']}`",
        f"- Kind: `{payload['kind']}`",
        f"- Status: `{payload['status']}`",
        f"- Tags: {tags}",
        f"- Updated: `{payload['updated_at']}`",
        "",
        "## Summary",
        "",
        payload["summary"].strip(),
        "",
        "## Evidence",
        "",
    ]
    if evidence:
        for item in evidence:
            lines.append(f"- `{item}`")
    else:
        lines.append("- None recorded.")
    lines.extend(["", "## Model References", ""])
    if model_refs:
        for item in model_refs:
            lines.append(f"- `{item}`")
    else:
        lines.append("- None recorded.")
    lines.extend(["", "## Body", "", body.rstrip(), ""])
    return "\n".join(lines)


def body_from_note_markdown(text: str) -> str:
    match = re.search(r"^## Body\s*$", text, re.MULTILINE)
    if not match:
        return text.strip()
    return text[match.end() :].strip()


def upsert_tag(conn: Any, tag: dict[str, Any]) -> None:
    conn.execute(
        """
        INSERT INTO corpus_tags(tag_key, facet, value)
        VALUES (?, ?, ?)
        ON CONFLICT(tag_key) DO UPDATE SET facet=excluded.facet, value=excluded.value
        """,
        (tag["key"], tag["facet"], tag["value"]),
    )


def document_exists(root: Path, doc_id: str) -> bool:
    workspace_db.initialize_workspace_db(root)
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        row = conn.execute("SELECT 1 FROM corpus_documents WHERE doc_id = ?", (doc_id,)).fetchone()
    return bool(row)


def upsert_document(root: Path, payload: dict[str, Any], body: str, *, allow_update: bool) -> None:
    workspace_db.initialize_workspace_db(root)
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        doc_id = payload["doc_id"]
        exists = conn.execute("SELECT 1 FROM corpus_documents WHERE doc_id = ?", (doc_id,)).fetchone()
        if exists and not allow_update:
            raise SystemExit(f"corpus document already exists: {doc_id}; use update-note to modify it")
        if allow_update and workspace_db.fts5_enabled(conn):
            conn.execute("DELETE FROM corpus_search WHERE doc_id = ?", (doc_id,))
        if allow_update:
            conn.execute("DELETE FROM corpus_document_tags WHERE doc_id = ?", (doc_id,))
        payload["line_count"] = count_lines(body)
        payload["word_count"] = count_words(body)
        raw_json = json.dumps(payload, sort_keys=True)
        values = (
            doc_id,
            payload["title"],
            payload["kind"],
            payload["status"],
            payload["summary"],
            payload["body_path"],
            payload["line_count"],
            payload["word_count"],
            payload["created_at"],
            payload["updated_at"],
            raw_json,
        )
        if allow_update:
            conn.execute(
                """
                INSERT INTO corpus_documents(
                  doc_id, title, kind, status, summary, body_path, line_count, word_count,
                  created_at, updated_at, raw_json
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(doc_id) DO UPDATE SET
                  title=excluded.title,
                  kind=excluded.kind,
                  status=excluded.status,
                  summary=excluded.summary,
                  body_path=excluded.body_path,
                  line_count=excluded.line_count,
                  word_count=excluded.word_count,
                  updated_at=excluded.updated_at,
                  raw_json=excluded.raw_json
                """,
                values,
            )
        else:
            try:
                conn.execute(
                    """
                    INSERT INTO corpus_documents(
                      doc_id, title, kind, status, summary, body_path, line_count, word_count,
                      created_at, updated_at, raw_json
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    values,
                )
            except sqlite3.IntegrityError as exc:
                raise SystemExit(f"corpus document already exists: {doc_id}; use update-note to modify it") from exc
        tags_text_parts: list[str] = []
        for tag in payload.get("tags", []):
            upsert_tag(conn, tag)
            conn.execute(
                """
                INSERT INTO corpus_document_tags(doc_id, tag_key, weight, source)
                VALUES (?, ?, ?, ?)
                ON CONFLICT(doc_id, tag_key) DO UPDATE SET
                  weight=excluded.weight,
                  source=excluded.source
                """,
                (doc_id, tag["key"], float(tag.get("weight", 1.0)), str(tag.get("source", "manual"))),
            )
            tags_text_parts.extend([tag["facet"], tag["value"], tag["key"]])
        if workspace_db.fts5_enabled(conn):
            conn.execute(
                "INSERT INTO corpus_search(doc_id, title, summary, body, tags) VALUES (?, ?, ?, ?, ?)",
                (doc_id, payload["title"], payload["summary"], body, " ".join(tags_text_parts)),
            )
        conn.commit()


def get_document(root: Path, doc_id: str) -> dict[str, Any]:
    workspace_db.initialize_workspace_db(root)
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        row = conn.execute("SELECT raw_json FROM corpus_documents WHERE doc_id = ?", (doc_id,)).fetchone()
    if not row:
        raise SystemExit(f"corpus document not found: {doc_id}")
    return json.loads(row["raw_json"])


def document_body(root: Path, payload: dict[str, Any]) -> str:
    path = workspace_path(root, payload["body_path"], "body path")
    return body_from_note_markdown(read_text_file(path))


def list_documents(root: Path, *, tag_filters: list[dict[str, Any]] | None = None, kind: str | None = None, status: str | None = None) -> list[dict[str, Any]]:
    workspace_db.initialize_workspace_db(root)
    clauses = ["1=1"]
    params: list[Any] = []
    if kind:
        clauses.append("kind = ?")
        params.append(kind)
    if status:
        clauses.append("status = ?")
        params.append(status)
    for tag in tag_filters or []:
        clauses.append(
            "EXISTS (SELECT 1 FROM corpus_document_tags cdt WHERE cdt.doc_id = corpus_documents.doc_id AND cdt.tag_key = ?)"
        )
        params.append(tag["key"])
    sql = "SELECT raw_json FROM corpus_documents WHERE " + " AND ".join(clauses) + " ORDER BY updated_at DESC, doc_id"
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        rows = conn.execute(sql, params).fetchall()
    return [json.loads(row["raw_json"]) for row in rows]


def search_documents(root: Path, query: str, *, tag_filters: list[dict[str, Any]], kind: str | None, status: str | None, limit: int) -> list[tuple[float, dict[str, Any]]]:
    workspace_db.initialize_workspace_db(root)
    tag_filters = tag_filters or []
    limit = max(1, limit)
    query_text = fts_query(query)
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        clauses = []
        params: list[Any] = []
        if kind:
            clauses.append("corpus_documents.kind = ?")
            params.append(kind)
        if status:
            clauses.append("corpus_documents.status = ?")
            params.append(status)
        for tag in tag_filters:
            clauses.append(
                "EXISTS (SELECT 1 FROM corpus_document_tags cdt WHERE cdt.doc_id = corpus_documents.doc_id AND cdt.tag_key = ?)"
            )
            params.append(tag["key"])
        where_filters = " AND ".join(clauses)
        if workspace_db.fts5_enabled(conn) and query_text:
            sql = (
                "SELECT corpus_documents.raw_json AS raw_json, bm25(corpus_search) AS rank "
                "FROM corpus_search JOIN corpus_documents USING(doc_id) "
                "WHERE corpus_search MATCH ?"
            )
            query_params: list[Any] = [query_text]
            if where_filters:
                sql += f" AND {where_filters}"
                query_params.extend(params)
            sql += " ORDER BY rank ASC LIMIT ?"
            query_params.append(limit)
            rows = conn.execute(sql, query_params).fetchall()
            return [(round(-float(row["rank"]), 6), json.loads(row["raw_json"])) for row in rows]
        docs = list_documents(root, tag_filters=tag_filters, kind=kind, status=status)
    wanted = token_set(query)
    scored: list[tuple[float, dict[str, Any]]] = []
    for doc in docs:
        body = document_body(root, doc)
        haystack = " ".join(
            [
                doc.get("doc_id", ""),
                doc.get("title", ""),
                doc.get("kind", ""),
                doc.get("status", ""),
                doc.get("summary", ""),
                body,
                " ".join(tag["key"] for tag in doc.get("tags", [])),
            ]
        )
        overlap = wanted & token_set(haystack)
        if overlap or not wanted:
            scored.append((float(len(overlap)), doc))
    scored.sort(key=lambda item: (item[0], item[1].get("updated_at", "")), reverse=True)
    return scored[:limit]


def tag_counts(root: Path) -> list[dict[str, Any]]:
    workspace_db.initialize_workspace_db(root)
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        rows = conn.execute(
            """
            SELECT corpus_tags.facet, corpus_tags.value, corpus_tags.tag_key, COUNT(corpus_document_tags.doc_id) AS count
            FROM corpus_tags
            LEFT JOIN corpus_document_tags USING(tag_key)
            GROUP BY corpus_tags.tag_key
            ORDER BY corpus_tags.facet, count DESC, corpus_tags.value
            """
        ).fetchall()
    return [
        {"facet": str(row["facet"]), "value": str(row["value"]), "key": str(row["tag_key"]), "count": int(row["count"])}
        for row in rows
    ]


def upsert_edge(root: Path, payload: dict[str, Any], *, allow_update: bool) -> None:
    errors, warnings = validate_edge_payload(payload)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if errors:
        raise SystemExit("\n".join(errors))
    workspace_db.initialize_workspace_db(root)
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        for doc_id in (payload["src_doc_id"], payload["dst_doc_id"]):
            row = conn.execute("SELECT doc_id FROM corpus_documents WHERE doc_id = ?", (doc_id,)).fetchone()
            if not row:
                raise SystemExit(f"edge references unknown document: {doc_id}")
        values = (
            payload["edge_id"],
            payload["src_doc_id"],
            payload["predicate"],
            payload["dst_doc_id"],
            payload["status"],
            payload["confidence"],
            payload.get("evidence", ""),
            payload.get("note", ""),
            payload["created_at"],
            payload["updated_at"],
            json.dumps(payload, sort_keys=True),
        )
        if allow_update:
            conn.execute(
                """
                INSERT INTO corpus_edges(
                  edge_id, src_doc_id, predicate, dst_doc_id, status, confidence,
                  evidence, note, created_at, updated_at, raw_json
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(edge_id) DO UPDATE SET
                  src_doc_id=excluded.src_doc_id,
                  predicate=excluded.predicate,
                  dst_doc_id=excluded.dst_doc_id,
                  status=excluded.status,
                  confidence=excluded.confidence,
                  evidence=excluded.evidence,
                  note=excluded.note,
                  updated_at=excluded.updated_at,
                  raw_json=excluded.raw_json
                """,
                values,
            )
        else:
            try:
                conn.execute(
                    """
                    INSERT INTO corpus_edges(
                      edge_id, src_doc_id, predicate, dst_doc_id, status, confidence,
                      evidence, note, created_at, updated_at, raw_json
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    values,
                )
            except sqlite3.IntegrityError as exc:
                raise SystemExit(f"corpus edge already exists: {payload['edge_id']}; pass --edge-id to update it") from exc
        conn.commit()


def list_edges(root: Path, doc_id: str | None = None) -> list[dict[str, Any]]:
    workspace_db.initialize_workspace_db(root)
    params: list[Any] = []
    where = ""
    if doc_id:
        where = "WHERE src_doc_id = ? OR dst_doc_id = ?"
        params.extend([doc_id, doc_id])
    with workspace_db.connect(root) as conn:
        workspace_db.ensure_schema(conn)
        rows = conn.execute(f"SELECT raw_json FROM corpus_edges {where} ORDER BY updated_at DESC, edge_id", params).fetchall()
    return [json.loads(row["raw_json"]) for row in rows]


def graph_neighbors(root: Path, doc_ids: list[str], limit: int) -> list[dict[str, Any]]:
    if not doc_ids:
        return []
    seen_docs = set(doc_ids)
    neighbors: list[dict[str, Any]] = []
    for edge in list_edges(root):
        other = None
        if edge["src_doc_id"] in seen_docs:
            other = edge["dst_doc_id"]
        elif edge["dst_doc_id"] in seen_docs:
            other = edge["src_doc_id"]
        if other and other not in seen_docs:
            try:
                doc = get_document(root, other)
            except SystemExit:
                continue
            neighbors.append({"edge": edge, "document": doc})
            seen_docs.add(other)
        if len(neighbors) >= limit:
            break
    return neighbors


def diversify_results(results: list[tuple[float, dict[str, Any]]], facets: list[str], limit: int) -> list[tuple[float, dict[str, Any]]]:
    if not facets:
        return results[:limit]
    selected: list[tuple[float, dict[str, Any]]] = []
    selected_ids: set[str] = set()
    buckets: dict[str, int] = defaultdict(int)
    per_bucket_soft_cap = max(1, limit // max(2, min(limit, len(facets) * 2)))

    def bucket_for(doc: dict[str, Any]) -> str:
        tags = doc.get("tags", [])
        values = []
        for facet in facets:
            facet_values = sorted(tag["value"] for tag in tags if tag.get("facet") == facet)
            if facet_values:
                values.append(f"{facet}={facet_values[0]}")
        return "|".join(values) or "untagged"

    for score, doc in results:
        bucket = bucket_for(doc)
        if buckets[bucket] < per_bucket_soft_cap:
            selected.append((score, doc))
            selected_ids.add(doc["doc_id"])
            buckets[bucket] += 1
        if len(selected) >= limit:
            return selected
    for score, doc in results:
        if doc["doc_id"] not in selected_ids:
            selected.append((score, doc))
            if len(selected) >= limit:
                break
    return selected


def format_doc_line(doc: dict[str, Any], score: float | None = None) -> str:
    score_text = f" score={score}" if score is not None else ""
    tags = ", ".join(tag["key"] for tag in doc.get("tags", [])[:6])
    return f"- `{doc['doc_id']}`{score_text} `{doc['kind']}` `{doc['status']}` {doc['title']} [{tags}]"


def render_context_pack(root: Path, query: str, results: list[tuple[float, dict[str, Any]]], *, facets: list[str], limit: int) -> str:
    selected = diversify_results(results, facets, limit)
    selected_docs = [doc for _, doc in selected]
    selected_ids = [doc["doc_id"] for doc in selected_docs]
    neighbors = graph_neighbors(root, selected_ids, max(3, limit // 2))
    tag_counter: Counter[str] = Counter()
    for doc in selected_docs:
        for tag in doc.get("tags", []):
            tag_counter[tag["key"]] += 1
    all_counts = tag_counts(root)
    underexplored = [
        item for item in all_counts if item["count"] > 0 and item["key"] not in tag_counter
    ][:10]
    unknowns = [
        doc for doc in list_documents(root, kind="open-question") if doc["doc_id"] not in selected_ids
    ][:5]
    negative = [
        doc for doc in list_documents(root, kind="negative-result") if doc["doc_id"] not in selected_ids
    ][:5]
    lines = [
        "# MaxTAC Corpus Orientation Pack",
        "",
        f"- Query: {query}",
        f"- Diversify by: {', '.join(facets) if facets else 'none'}",
        "",
        "## Primary Notes",
        "",
    ]
    if not selected:
        lines.append("No matching corpus notes.")
    for score, doc in selected:
        lines.append(format_doc_line(doc, score))
        lines.append(f"  Summary: {doc['summary']}")
    lines.extend(["", "## Graph Neighbors", ""])
    if not neighbors:
        lines.append("No graph neighbors recorded.")
    for item in neighbors:
        edge = item["edge"]
        doc = item["document"]
        lines.append(
            f"- `{doc['doc_id']}` via `{edge['predicate']}` `{edge['src_doc_id']}` -> `{edge['dst_doc_id']}`: {doc['title']}"
        )
    lines.extend(["", "## Negative Knowledge", ""])
    if not negative:
        lines.append("No adjacent negative-result notes found.")
    for doc in negative:
        lines.append(format_doc_line(doc))
        lines.append(f"  Summary: {doc['summary']}")
    lines.extend(["", "## Open Questions", ""])
    if not unknowns:
        lines.append("No open-question notes found.")
    for doc in unknowns:
        lines.append(format_doc_line(doc))
        lines.append(f"  Summary: {doc['summary']}")
    lines.extend(["", "## Underexplored Tags", ""])
    if not underexplored:
        lines.append("No underexplored tags found.")
    for item in underexplored:
        lines.append(f"- `{item['key']}` ({item['count']} note(s))")
    lines.extend(
        [
            "",
            "## Guidance",
            "",
            "- Read primary notes before adding new corpus content.",
            "- Prefer updating or linking an existing note when the new fact refines, contradicts, or supersedes it.",
            "- If continuing in one subsystem, name the reason and checkpoint; otherwise pivot to an adjacent underexplored tag or open question.",
            "",
        ]
    )
    return "\n".join(lines)


def render_views(root: Path) -> dict[str, str]:
    docs = list_documents(root)
    edges = list_edges(root)
    counts = tag_counts(root)
    by_kind: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for doc in docs:
        by_kind[doc["kind"]].append(doc)
    index_lines = [
        GENERATED_NOTICE,
        "# Research Corpus Index",
        "",
        f"- Documents: {len(docs)}",
        f"- Edges: {len(edges)}",
        "",
        "## Recent Notes",
        "",
    ]
    for doc in docs[:25]:
        index_lines.append(format_doc_line(doc))
        index_lines.append(f"  Summary: {doc['summary']}")
    index_lines.extend(["", "## By Kind", ""])
    for kind in sorted(by_kind):
        index_lines.append(f"### {kind}")
        index_lines.append("")
        for doc in by_kind[kind]:
            index_lines.append(format_doc_line(doc))
        index_lines.append("")

    facet_lines = [GENERATED_NOTICE, "# Corpus Facets", ""]
    current_facet = None
    for item in counts:
        if current_facet != item["facet"]:
            current_facet = item["facet"]
            facet_lines.extend([f"## {current_facet}", ""])
        facet_lines.append(f"- `{item['value']}`: {item['count']} note(s)")
    if not counts:
        facet_lines.append("No tags recorded.")
    facet_lines.append("")

    question_lines = [GENERATED_NOTICE, "# Open Questions And Negative Knowledge", "", "## Open Questions", ""]
    open_docs = [doc for doc in docs if doc["kind"] == "open-question"]
    if not open_docs:
        question_lines.append("No open-question notes recorded.")
    for doc in open_docs:
        question_lines.append(format_doc_line(doc))
        question_lines.append(f"  Summary: {doc['summary']}")
    question_lines.extend(["", "## Negative Results", ""])
    negative_docs = [doc for doc in docs if doc["kind"] == "negative-result"]
    if not negative_docs:
        question_lines.append("No negative-result notes recorded.")
    for doc in negative_docs:
        question_lines.append(format_doc_line(doc))
        question_lines.append(f"  Summary: {doc['summary']}")

    graph_lines = ["graph TD"]
    if not docs:
        graph_lines.append('  empty["No corpus notes"]')
    for doc in docs:
        node = doc["doc_id"].replace("-", "_")
        label = f"{doc['doc_id']}: {doc['title']}".replace('"', "'")
        graph_lines.append(f'  {node}["{label}"]')
    for edge in edges:
        src = edge["src_doc_id"].replace("-", "_")
        dst = edge["dst_doc_id"].replace("-", "_")
        pred = edge["predicate"].replace('"', "'")
        graph_lines.append(f"  {src} -->|{pred}| {dst}")

    return {
        "index.md": "\n".join(index_lines).rstrip() + "\n",
        "facets.md": "\n".join(facet_lines).rstrip() + "\n",
        "open-questions.md": "\n".join(question_lines).rstrip() + "\n",
        "graph.mmd": "\n".join(graph_lines).rstrip() + "\n",
    }


def cmd_init(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    ensure_dirs(root)
    workspace_db.initialize_workspace_db(root)
    print(f"Corpus root: {root / 'research'}")
    for name, path in corpus_dirs(root).items():
        if name == "research":
            continue
        print(f"- {name}: {relative_to_root(root, path)}")


def note_payload_from_args(root: Path, args: argparse.Namespace, body: str, *, existing: dict[str, Any] | None = None) -> dict[str, Any]:
    timestamp = now()
    doc_id = args.doc_id or (existing or {}).get("doc_id") or next_id(root, "corpus_documents", "doc_id", DOC_PREFIX)
    body_path = f"research/notes/{doc_id}.md"
    payload = dict(existing or {})
    payload.update(
        {
            "doc_id": doc_id,
            "title": args.title if args.title is not None else payload.get("title", ""),
            "kind": args.kind if args.kind is not None else payload.get("kind", "reference"),
            "status": args.status if args.status is not None else payload.get("status", "draft"),
            "summary": args.summary if args.summary is not None else payload.get("summary", ""),
            "body_path": body_path,
            "updated_at": timestamp,
            "evidence": parse_repeated(args.evidence) if args.evidence is not None else payload.get("evidence", []),
            "model_refs": parse_repeated(args.model_ref) if args.model_ref is not None else payload.get("model_refs", []),
        }
    )
    payload.setdefault("created_at", timestamp)
    if args.tag is not None:
        payload["tags"] = parse_tags(args.tag)
    else:
        payload.setdefault("tags", [])
    payload["line_count"] = count_lines(body)
    payload["word_count"] = count_words(body)
    return payload


def body_from_args(args: argparse.Namespace) -> str:
    if args.body_file:
        return read_text_file(Path(args.body_file).expanduser())
    if args.body:
        return args.body
    if not sys.stdin.isatty():
        data = sys.stdin.read()
        if data.strip():
            return data
    raise SystemExit("body is required via --body, --body-file, or stdin")


def cmd_add_note(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    ensure_dirs(root)
    body = body_from_args(args)
    payload = note_payload_from_args(root, args, body)
    errors, warnings = validate_doc_payload(payload, body, strict=not args.allow_thin)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if errors:
        raise SystemExit("\n".join(errors))
    if document_exists(root, payload["doc_id"]):
        raise SystemExit(f"corpus document already exists: {payload['doc_id']}; use update-note to modify it")
    note_path = workspace_path(root, payload["body_path"], "note path")
    write_text_file(note_path, render_note_markdown(payload, body))
    upsert_document(root, payload, body, allow_update=False)
    print(payload["doc_id"])


def cmd_update_note(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    ensure_dirs(root)
    existing = get_document(root, args.doc_id)
    current_body = document_body(root, existing)
    if args.append:
        body = current_body.rstrip() + "\n\n" + args.append.strip()
    elif args.body_file or args.body or not sys.stdin.isatty():
        body = body_from_args(args)
    else:
        body = current_body
    payload = note_payload_from_args(root, args, body, existing=existing)
    if args.add_tag:
        existing_tags = {tag["key"]: tag for tag in payload.get("tags", [])}
        for tag in parse_tags(args.add_tag):
            existing_tags[tag["key"]] = tag
        payload["tags"] = list(existing_tags.values())
    errors, warnings = validate_doc_payload(payload, body, strict=not args.allow_thin)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if errors:
        raise SystemExit("\n".join(errors))
    note_path = workspace_path(root, payload["body_path"], "note path")
    write_text_file(note_path, render_note_markdown(payload, body))
    upsert_document(root, payload, body, allow_update=True)
    print(payload["doc_id"])


def cmd_import_file(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    source = workspace_path(root, args.markdown_file, "markdown file")
    text = read_text_file(source)
    body = body_from_note_markdown(text)
    title = args.title
    if not title:
        match = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
        title = match.group(1).strip() if match else source.stem.replace("-", " ").title()
    summary = args.summary or body.splitlines()[0][:240] if body.splitlines() else f"Imported from {relative_to_root(root, source)}."
    import_args = argparse.Namespace(
        root=args.root,
        doc_id=args.doc_id,
        title=title,
        kind=args.kind,
        status=args.status,
        summary=summary,
        tag=args.tag,
        evidence=[relative_to_root(root, source), *(args.evidence or [])],
        model_ref=args.model_ref,
    )
    payload = note_payload_from_args(root, import_args, body)
    errors, warnings = validate_doc_payload(payload, body, strict=not args.allow_thin)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if errors:
        raise SystemExit("\n".join(errors))
    if document_exists(root, payload["doc_id"]):
        raise SystemExit(f"corpus document already exists: {payload['doc_id']}; use update-note to modify it")
    note_path = workspace_path(root, payload["body_path"], "note path")
    write_text_file(note_path, render_note_markdown(payload, body))
    upsert_document(root, payload, body, allow_update=False)
    if args.move:
        archive_dir = corpus_dirs(root)["artifacts"] / "imported-markdown"
        archive_dir.mkdir(parents=True, exist_ok=True)
        destination = archive_dir / source.name
        if destination.exists():
            destination = archive_dir / f"{source.stem}-{payload['doc_id']}{source.suffix}"
        shutil.move(str(source), destination)
        print(f"moved source to {relative_to_root(root, destination)}")
    print(payload["doc_id"])


def cmd_link(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    timestamp = now()
    allow_update = bool(args.edge_id)
    edge_id = args.edge_id or next_id(root, "corpus_edges", "edge_id", EDGE_PREFIX)
    payload = {
        "edge_id": edge_id,
        "src_doc_id": args.src,
        "predicate": args.predicate.strip().lower().replace(" ", "_"),
        "dst_doc_id": args.dst,
        "status": args.status,
        "confidence": args.confidence,
        "evidence": args.evidence or "",
        "note": args.note or "",
        "created_at": timestamp,
        "updated_at": timestamp,
    }
    upsert_edge(root, payload, allow_update=allow_update)
    print(edge_id)


def cmd_search(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    tags = parse_tags(args.tag)
    results = search_documents(root, args.query or "", tag_filters=tags, kind=args.kind, status=args.status, limit=args.limit)
    if args.json:
        print(json.dumps([{"score": score, "document": doc} for score, doc in results], indent=2))
        return
    if not results:
        print("No corpus notes found.")
        return
    for score, doc in results:
        print(format_doc_line(doc, score))
        print(f"  Summary: {doc['summary']}")


def cmd_list(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    docs = list_documents(root, tag_filters=parse_tags(args.tag), kind=args.kind, status=args.status)
    for doc in docs[: args.limit or None]:
        print(format_doc_line(doc))
        print(f"  Summary: {doc['summary']}")
    if not docs:
        print("No corpus notes found.")


def cmd_show(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    doc = get_document(root, args.doc_id)
    path = workspace_path(root, doc["body_path"], "note path")
    if args.metadata:
        print(json.dumps(doc, indent=2))
    else:
        print(read_text_file(path), end="")


def cmd_orient(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    results = search_documents(
        root,
        args.query or "",
        tag_filters=parse_tags(args.tag),
        kind=args.kind,
        status=args.status,
        limit=max(args.limit * 3, args.limit),
    )
    facets = [item.strip() for item in (args.diversify_by or "").split(",") if item.strip()]
    pack = render_context_pack(root, args.query or "", results, facets=facets, limit=args.limit)
    if args.output:
        write_text_file(Path(args.output), pack)
    else:
        print(pack)


def cmd_compile_views(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    ensure_dirs(root)
    views = render_views(root)
    view_dir = corpus_dirs(root)["views"]
    for filename, text in views.items():
        write_text_file(view_dir / filename, text)
        print(relative_to_root(root, view_dir / filename))


def cmd_lint(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    docs = list_documents(root)
    errors: list[str] = []
    warnings: list[str] = []
    for doc in docs:
        body = document_body(root, doc)
        doc_errors, doc_warnings = validate_doc_payload(doc, body, strict=True)
        errors.extend(f"{doc['doc_id']}: {error}" for error in doc_errors)
        warnings.extend(f"{doc['doc_id']}: {warning}" for warning in doc_warnings)
    legacy = legacy_markdown(root)
    if legacy:
        warnings.append(
            f"{len(legacy)} markdown file(s) live outside research/notes, research/views, or research/artifacts"
        )
    for warning in warnings:
        print(f"warning: {warning}")
    for error in errors:
        print(f"error: {error}")
    if errors or (args.strict and warnings):
        raise SystemExit(1)
    print(f"Corpus lint ok: {len(docs)} note(s)")


def legacy_markdown(root: Path) -> list[Path]:
    research = root / "research"
    if not research.exists():
        return []
    allowed_roots = {"notes", "views", "artifacts"}
    result: list[Path] = []
    for path in sorted(research.rglob("*.md")):
        try:
            parts = path.relative_to(research).parts
        except ValueError:
            continue
        if not parts:
            continue
        if parts[0] not in allowed_roots:
            result.append(path)
    return result


def cmd_tags(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    counts = tag_counts(root)
    if args.json:
        print(json.dumps(counts, indent=2))
        return
    for item in counts:
        print(f"- `{item['key']}` {item['count']} note(s)")
    if not counts:
        print("No tags recorded.")


def add_root(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--root", default=".")


def add_note_args(parser: argparse.ArgumentParser, *, update: bool = False) -> None:
    if update:
        parser.add_argument("doc_id")
    else:
        parser.add_argument("--doc-id")
    parser.add_argument("--title")
    parser.add_argument("--kind", choices=DOC_KINDS)
    parser.add_argument("--status", choices=DOC_STATUSES)
    parser.add_argument("--summary")
    parser.add_argument("--body")
    parser.add_argument("--body-file")
    parser.add_argument("--tag", action="append", help="Facet tag such as subsystem=export-api or boundary=tenant")
    parser.add_argument("--evidence", action="append")
    parser.add_argument("--model-ref", action="append")
    parser.add_argument("--allow-thin", action="store_true", help="Allow fewer tags for temporary drafts")


def base_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="MaxTAC faceted research corpus helper")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init = subparsers.add_parser("init", help="Initialize corpus directories and SQLite tables")
    add_root(init)
    init.set_defaults(func=cmd_init)

    add = subparsers.add_parser("add-note", help="Create a canonical corpus note")
    add_root(add)
    add_note_args(add)
    add.set_defaults(func=cmd_add_note)

    update = subparsers.add_parser("update-note", help="Update a corpus note")
    add_root(update)
    add_note_args(update, update=True)
    update.add_argument("--append", help="Append text to the current note body")
    update.add_argument("--add-tag", action="append", help="Add tags without replacing existing tags")
    update.set_defaults(func=cmd_update_note)

    import_file = subparsers.add_parser("import-file", help="Import existing markdown into a canonical corpus note")
    add_root(import_file)
    import_file.add_argument("markdown_file")
    import_file.add_argument("--doc-id")
    import_file.add_argument("--title")
    import_file.add_argument("--kind", choices=DOC_KINDS, default="reference")
    import_file.add_argument("--status", choices=DOC_STATUSES, default="draft")
    import_file.add_argument("--summary")
    import_file.add_argument("--tag", action="append", required=True)
    import_file.add_argument("--evidence", action="append")
    import_file.add_argument("--model-ref", action="append")
    import_file.add_argument("--allow-thin", action="store_true")
    import_file.add_argument("--move", action="store_true", help="Move source markdown under research/artifacts/imported-markdown")
    import_file.set_defaults(func=cmd_import_file)

    link = subparsers.add_parser("link", help="Create or update a typed graph edge between corpus notes")
    add_root(link)
    link.add_argument("src")
    link.add_argument("predicate")
    link.add_argument("dst")
    link.add_argument("--edge-id")
    link.add_argument("--status", choices=EDGE_STATUSES, default="candidate")
    link.add_argument("--confidence", choices=CONFIDENCES, default="unknown")
    link.add_argument("--evidence")
    link.add_argument("--note")
    link.set_defaults(func=cmd_link)

    search = subparsers.add_parser("search", help="Search corpus notes with FTS and metadata filters")
    add_root(search)
    search.add_argument("--query", default="")
    search.add_argument("--tag", action="append")
    search.add_argument("--kind", choices=DOC_KINDS)
    search.add_argument("--status", choices=DOC_STATUSES)
    search.add_argument("--limit", type=int, default=10)
    search.add_argument("--json", action="store_true")
    search.set_defaults(func=cmd_search)

    list_cmd = subparsers.add_parser("list", help="List corpus notes")
    add_root(list_cmd)
    list_cmd.add_argument("--tag", action="append")
    list_cmd.add_argument("--kind", choices=DOC_KINDS)
    list_cmd.add_argument("--status", choices=DOC_STATUSES)
    list_cmd.add_argument("--limit", type=int, default=0)
    list_cmd.set_defaults(func=cmd_list)

    show = subparsers.add_parser("show", help="Show a corpus note")
    add_root(show)
    show.add_argument("doc_id")
    show.add_argument("--metadata", action="store_true")
    show.set_defaults(func=cmd_show)

    orient = subparsers.add_parser("orient", help="Create an anti-tunnel orientation pack")
    add_root(orient)
    orient.add_argument("--query", default="")
    orient.add_argument("--tag", action="append")
    orient.add_argument("--kind", choices=DOC_KINDS)
    orient.add_argument("--status", choices=DOC_STATUSES)
    orient.add_argument("--limit", type=int, default=8)
    orient.add_argument("--diversify-by", default="subsystem,boundary,knowledge-kind")
    orient.add_argument("--output")
    orient.set_defaults(func=cmd_orient)

    compile_views = subparsers.add_parser("compile-views", help="Generate research/views markdown and graph files")
    add_root(compile_views)
    compile_views.set_defaults(func=cmd_compile_views)

    lint = subparsers.add_parser("lint", help="Validate corpus notes and warn about legacy research markdown")
    add_root(lint)
    lint.add_argument("--strict", action="store_true")
    lint.set_defaults(func=cmd_lint)

    tags = subparsers.add_parser("tags", help="List tag counts")
    add_root(tags)
    tags.add_argument("--json", action="store_true")
    tags.set_defaults(func=cmd_tags)

    return parser


def main() -> None:
    parser = base_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
